### PR TITLE
Build: re-add an option to disable building documentation

### PR DESCRIPTION
**Pull request by eli-schwartz**

### CODE REVIEW

**Comment by clefebvre** [comment]
Wouldn't this default to disabling docs, if not specified?

In other words, you changed the default build configuration from having docs, to not having docs... should you not introduce a disable-docs option instead, to preserve the same default behaviour as before?

**Comment by eli-schwartz** [comment]
meson options default to true, see http://mesonbuild.com/Build-options.html and the output of `meson configure` after running meson without specifying options.

**Comment by clefebvre** [comment]
Cool, why not.

**Comment by eli-schwartz** [comment]
I force-pushed a change so that if enable-doc is set, it will first check to see whether gtkdoc-scan exists, and issue a warning otherwise.

AFAICT there is no way for meson to report on whether, say, gnome.gtkdoc() is functional.

**Comment by clefebvre** [comment]
Hi @eli-schwartz,

That looks good, but why use an option? Why not just rely on the presence of the binary? Distributions can then either add it to their build-deps or not.

**Comment by clefebvre** [comment]
Also, you've definitely changed the default behaviour there....

**Comment by clefebvre** [comment]
Hi @eli-schwartz, @mtwebster added an option for this and pushed to master.

**Comment by mtwebster** [comment]
Ah shoot sorry, I missed this PR, we had some internal discussion about this and I just added it.

**Comment by eli-schwartz** [comment]
The purpose of the option is to allow people to decide they do not want to bother building it, regardless of whether they have gtk-doc installed for unrelated reasons (e.g. personal, non-distro, non-clean-chroot builds).

The purpose of checking for the binary, is to try to gracefully fall back on assuming you don't want it rather than erroring out, if a) the option is enabled by default, and b) gtk-doc is not installed. The merged change works for me, though.
(I didn't know whether you wanted it enabled by default, so I figured I would preserve the status quo. Also the previous autotools setup seems to have had it enabled by default.)

**Pull request closed without merging**
